baseURL: http://mmmdata.io
theme: hugo-theme-introduction
DefaultContentLanguage: en
params:
  dateFormat: Jan 2, 2006
  email: ian.hussey@icloud.com
  fadeIn: no
  fadeInIndex: no
  favicon: /img/fav.ico
  giscus:
    category: Comments
    category-id: enter-category-id
    emit-metadata: '0'
    lang: en
    mapping: pathname
    reactions-enabled: '1'
    repo-id: enter-repo-id
    theme: light
  home:
    allPostsArchiveFormat: yes
    introHeight: fullheight
    localTime: yes
    numberOfProjectsToShow: 3
    showAllPosts: no
    showLatest: yes
    timeFormat: en-US
    timeZone: Eurpoe/Brussels
  projects:
    useTwoColumns: no
  share:
    facebook: no
    pinterest: no
    twitter: yes
    github: yes
  showRSSButton: no
  social:
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/ianhussey
    - icon: facebook-f
      icon_pack: fab
      url: https://facebook.com/
    - icon: linkedin-in
      icon_pack: fab
      url: https://www.linkedin.com/in/ian-hussey-phd
    - icon: paper-plane
      icon_pack: fas
      url: mailto:ian.hussey@icloud.com
    - html_attributes: rel="me"
      icon: mastodon
      icon_pack: fab
      url: https://mastodon.social/
  themeStyle: auto
taxonomies:
  series: series
  tag: tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: yes
    style: solarized-dark
    tabWidth: 4
languages:
  de:
    contentDir: content/de
    languageCode: de
    languageName: Deutsch
    params:
      dateFormat: 2. January 2006
      description: Beschreibung der Webseite
    title: Vorstellung
    weight: 2
  en:
    contentDir: content/en
    languageCode: en-us
    languageName: English
    params:
      description: Website Description
    title: Introduction
    weight: 0
  es:
    contentDir: content/es
    languageCode: es
    languageName: Español
    params:
      description: Descripcion del sitio web
    title: Introducción
    weight: 1
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
